server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  tomcat:
    uri-encoding: utf-8
    max-connections: 20
spring:
  h2:
    console:
      enabled: true
  kafka:
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 2000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: io.github.sejoung.kafka.dto.CustomMessage
            trusted:
              packages: io.github.sejoung.kafka.dto
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    listener:
      concurrency: 1
      ack-mode: manual
      type: single
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  jpa:
    show-sql: true
    open-in-view: false

topic:
  single: test-topic
  list: test-list-topic
  event: event-topic