GET http://localhost:8080/api/order/3/
Accept: application/json

###
PUT http://localhost:8080/api/order/
Accept: application/json

###
PATCH http://localhost:8080/api/order/4/payed
Accept: application/json